model:
  name: "LSTM_Attention"
  bidirectional: false
  lstm_hidden: 192
  lstm_layers: 3
  dropout: 0.3
  attn_heads: 2
  attn_dim: 128
  mlp_hidden: 128

training:
  lr: 0.0002576021731458815
  weight_decay: 7.985781895853134e-07
  batch_size: 256
  seq_len: 120
  optimizer: "adamw"
  loss: "mse"
  train_on: "log_return"
  predict_as: "price"
  epochs: 50
  seed: 42
  device: "cuda"

features:
  use_all_features: true
